import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/footer"; // Import the Footer component
import Navbar from "@/components/navbar"; // Import the Navbar component

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} flex flex-col min-h-screen`}> {/* Added flex flex-col min-h-screen */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar /> {/* Add Navbar here */}
          <main className="flex-grow">{children}</main> {/* Added flex-grow to main content */}
          <Footer /> {/* Add Footer here */}
        </ThemeProvider>
      </body>
    </html>
  );
}
